# .github/workflows/python-ci.yml

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Remainder of the workflow will be added in subsequent steps.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Steps will be added here in subsequent plan items
    - name: Checkout repository
      uses: actions/checkout@v3
      # This step is essential to allow the workflow to access the repository code.
      # Using v3 for actions/checkout, will update to v4 if needed, but v3 is widely used.

    - name: Set up Python
      uses: actions/setup-python@v4 # Using v4 of setup-python
      with:
        python-version: '3.11' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/
